# NumPy 和陣列導向的程式設計

`NumPy` 可以說是 Python 中最最標準的科學計算、數據分析套件。也因為 `NumPy` 的出現, 讓 Python 有了非常好的數據分析基礎, 一直到現在成為數據分析覇主。

In [2]:
import numpy as np

## 1. 陣列導向 101

科學計算一個很核心的概念叫 "array oriented" 的寫法。Array 是 `numpy` 標準的資料結構, 和 list 很像, 但就差了那麼一點點。而這一點點讓我們在計算上是無比的方便。

### 【暖身】 計算平均

某位同學期中考各科成績如下, 請幫他計算成績。

    grades = [77, 85, 56, 90, 66]
    
請計算平均。

In [13]:
gradess =[77, 85, 56, 90, 66]
a=0
for n in gradess:
    a=a+n
print(a/5)
    


74.8


### 【示範】陣列導向

In [14]:
grades = np.array([77, 85, 56, 90, 66])
grades.mean()

74.8

最大值

In [13]:
grades.max()

90

標準差

In [15]:
grades.std()

12.416118556135006

### 【暖身】 換算匯率

假設今天我想查查號稱 Pentax 三公主的 31mm, 43mm, 77mm 三隻 limited 鏡頭在美國賣多少。於是我去 B&H 查了他們的價格分別是:

    prices = [1096.95, 596.95, 896.95]
    
我又查了 Google 匯率 1 美金為 31.71 元。請把三支鏡頭的價格換算為台幣。

In [20]:
prices =[1096.95, 596.95, 896.95]
for i in range(0,3):
    prices[i]=prices[i]*31.71
print(prices)

[34784.2845, 18929.2845, 28442.2845]


先不管這實在有夠醜的數字, 我們要記得在科學計算中:

### 儘可能不要使用迴圈

這可能嗎?

### 【示範】陣列換算匯率

In [21]:
prices = np.array([1096.95, 596.95, 896.95])
prices*31.71

array([34784.2845, 18929.2845, 28442.2845])

哦哦, 傑克, 這太神奇了!

## 2. 其實 array 還有很多功能

### 【練習】 成績計算

一位老師成績這樣算的:

* 平時成績 20%
* 期中考   35%
* 期未考   45%

有位同學

* 平時成績 85 分
* 期中 70 分
* 期末 80 分

這位同學的學期成績是多少?

In [23]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])

這還不是我們要的最終成績啊!

In [24]:
grades*weights

array([17. , 24.5, 36. ])

### 【提示】 array 還有很多函數可以用

可以先打入

    weighted_grades.
    
先不要按 `enter` 或 `shift-enter`, 而是按 `tab`...


In [26]:
weightes_grades=weights*grades
weightes_grades.sum()

77.5

### 【技巧】 一行完成成績計算

In [27]:
np.dot(weights,grades)

77.5

## 3. 重要的 array 大變身!

我們在數據分析, 常常要改 array 的型式。

### 【練習】 一個 50 個數字的 array

先想辦法、用亂數做出 50 個數字的 array, 叫做 A 好了。

In [31]:
A=np.array(np.random.rand(50))
A

array([0.11125226, 0.03098701, 0.88886253, 0.27295641, 0.62049362,
       0.29308627, 0.34099632, 0.48038764, 0.95701129, 0.39847095,
       0.81341953, 0.46699379, 0.8504907 , 0.72142773, 0.83830869,
       0.80667294, 0.65932336, 0.79110084, 0.40429928, 0.17462785,
       0.06637422, 0.16398091, 0.91131982, 0.59242665, 0.63433598,
       0.56446699, 0.65545703, 0.73480877, 0.87261322, 0.32589185,
       0.72125251, 0.97746435, 0.62172156, 0.16397909, 0.75943541,
       0.33166862, 0.4727209 , 0.14266283, 0.81483831, 0.57622902,
       0.89611217, 0.50865536, 0.36216111, 0.90641476, 0.16639693,
       0.71062945, 0.59942766, 0.49487838, 0.05288403, 0.90469175])

0.737223397267063

### 【技巧】 檢查 A 的 `shape`

In [33]:
A.shape

(50,)

### 【技巧】 更改 A 的 shape

In [35]:
A.shape=(5,10)
A

array([[0.11125226, 0.03098701, 0.88886253, 0.27295641, 0.62049362,
        0.29308627, 0.34099632, 0.48038764, 0.95701129, 0.39847095],
       [0.81341953, 0.46699379, 0.8504907 , 0.72142773, 0.83830869,
        0.80667294, 0.65932336, 0.79110084, 0.40429928, 0.17462785],
       [0.06637422, 0.16398091, 0.91131982, 0.59242665, 0.63433598,
        0.56446699, 0.65545703, 0.73480877, 0.87261322, 0.32589185],
       [0.72125251, 0.97746435, 0.62172156, 0.16397909, 0.75943541,
        0.33166862, 0.4727209 , 0.14266283, 0.81483831, 0.57622902],
       [0.89611217, 0.50865536, 0.36216111, 0.90641476, 0.16639693,
        0.71062945, 0.59942766, 0.49487838, 0.05288403, 0.90469175]])

### 【技巧】 也可以用 `reshape`

但要注意, reshape 並沒有改原來的陣列。

In [36]:
A.reshape(5,10)

array([[0.11125226, 0.03098701, 0.88886253, 0.27295641, 0.62049362,
        0.29308627, 0.34099632, 0.48038764, 0.95701129, 0.39847095],
       [0.81341953, 0.46699379, 0.8504907 , 0.72142773, 0.83830869,
        0.80667294, 0.65932336, 0.79110084, 0.40429928, 0.17462785],
       [0.06637422, 0.16398091, 0.91131982, 0.59242665, 0.63433598,
        0.56446699, 0.65545703, 0.73480877, 0.87261322, 0.32589185],
       [0.72125251, 0.97746435, 0.62172156, 0.16397909, 0.75943541,
        0.33166862, 0.4727209 , 0.14266283, 0.81483831, 0.57622902],
       [0.89611217, 0.50865536, 0.36216111, 0.90641476, 0.16639693,
        0.71062945, 0.59942766, 0.49487838, 0.05288403, 0.90469175]])

### 【技巧】 拉平 `ravel`

雖然你想一想就知道可以用 `shape` 或 `reshape` 把多維陣列拉成一維。不過用 `ravel` 很潮。

In [38]:
A.ravel()

array([0.11125226, 0.03098701, 0.88886253, 0.27295641, 0.62049362,
       0.29308627, 0.34099632, 0.48038764, 0.95701129, 0.39847095,
       0.81341953, 0.46699379, 0.8504907 , 0.72142773, 0.83830869,
       0.80667294, 0.65932336, 0.79110084, 0.40429928, 0.17462785,
       0.06637422, 0.16398091, 0.91131982, 0.59242665, 0.63433598,
       0.56446699, 0.65545703, 0.73480877, 0.87261322, 0.32589185,
       0.72125251, 0.97746435, 0.62172156, 0.16397909, 0.75943541,
       0.33166862, 0.4727209 , 0.14266283, 0.81483831, 0.57622902,
       0.89611217, 0.50865536, 0.36216111, 0.90641476, 0.16639693,
       0.71062945, 0.59942766, 0.49487838, 0.05288403, 0.90469175])

## 4. 快速 array 生成法

### 【技巧】 都是 0 的 array

In [46]:
b=np.zeros((10,10))
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 【技巧】 都是 1 的 array

In [47]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 【技巧】單位矩陣

In [48]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 【技巧】給定範圍均勻生出 n 個點

In [49]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

### 【技巧】`range` 的 array 版

就是 `arange`。

In [52]:
np.arange(1,10,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

## 5. 超重要 `axis` 觀念

初學 `numpy` 很多人有點弄不清楚 `axis` 概念。其實掌握矩陣, 或很像矩陣的陣列都是「先列後行」就可以!

我們先弄個 array 來練習。

In [54]:
c=np.arange(10).reshape(2,5)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 【重點】 一列一列算下來是 `axis=0`

![axis=0](images/axis0.png)

In [56]:
c.sum(axis=0)

array([ 5,  7,  9, 11, 13])

### 【重點】 一行一行算過去是 `axis=1`

![axis=1](images/axis1.png)

In [57]:
c.sum(axis=1)

array([10, 35])

### 【提示】當然也有可能全部算

In [59]:
c.sum()

45

## 6. array 過濾器

篩出我們要的資料, 這樣的技巧非常重要!

### 【例子】篩出大於 0 的數

我們有個陣列, 想找出大於 0 的數。<br>
L = np.array([3, -2, -1, 5, 7, -3])

In [68]:
L = np.array([3, -2, -1, 5, 7, -3])

我們可以很白痴的自己判斷...<br>
c = np.array([True,False,False,True,True,False])

In [67]:
c = np.array([True,False,False,True,True,False])

這是做啥呢? 我們可以瞬間...

In [69]:
L[c]


array([3, 5, 7])

除了自己做很白痴, 這看來很厲害!

事實上我們可以叫 `numpy` 做!

In [72]:
L>0

array([ True,  True,  True])

這有點強, 我們還可以一次到位!

In [64]:
L=L[L>0]
L

array([3, 5, 7])

## 7. 次元切割刀

`numpy` 中 array 的切割法和 list 很像。

In [75]:
A=np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
A[4:7]

array([4, 5, 6])

### 【技巧】2維陣列切法

記得先列後行!

In [80]:
A.shape=(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

要所有的row, 切出行 1-3 位置。

In [82]:
A[:,1:3]

array([[1, 2],
       [6, 7]])

要所有的行col, 切出第 1 列row!

In [83]:
A[1,:]

array([5, 6, 7, 8, 9])

## 8. `NumPy` 的 `zip` 和 `unzip`

之前我們介紹 list 可以用 `zip` 和 `unzip` (其實還是 `zip`) 做到的資料格式變換, 在 array 中怎麼做呢?

![zip and unzip](images/zip.png)

### 【重點】array 的 `zip`

![array zip](images/arrzip.png)

In [85]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [87]:
A=np.c_[x,y]
A

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [89]:
np.r_[x,y]

array([1, 2, 3, 4, 5, 6, 7, 8])

### 【重點】array 的 `unzip`

這裡其實只需要用到 array 的切割法...

![array zip](images/arrunzip.png)

In [90]:
A[:,1]

array([5, 6, 7, 8])